### ISSUE TITLE
Bot stop working in the second button

### ISSUE THREAD

**Issue by xDarKSchneideR** [SmartBotBlack/goldmand#1]
Hello, bot can't claim in the second button and neither the cursed button.
Greetings =)

**Comment by LTW081** [comment]
Same issue here. 

Appears to stop on SELECTOR_APPROVE's "MINE NOW" button.
No errors present in console.

Any ideas on a fix?

**Comment by abyssofbirds** [comment]
We fixed script. But now we found new problem - periodically the page is reload, the script is deleted. Probably, you will not face this problem. There is no way we can fix this because it is a bug on goldmand's side.
